version: "3"
services:
  presto:
    image: shawnzhu/prestodb:329
    container_name: presto-server
    ports:
      - "8080:8080"
    volumes:
      - ./conf:/usr/lib/presto/default/etc
    networks:
      deploy:
        ipv4_address: 172.10.0.128

networks:
  deploy:
    external: true