version: "3"

services:
  # certbot-dnspod-init:
  #   image: darebeat/certbot
  #   container_name: certbot-dnspod-renew
  #   environment:
  #     - TZ=Asia/Shanghai
  #   volumes:
  #     - ./etc:/etc/letsencrypt:z
  #     - ./lib:/var/lib/letsencrypt:z
  #     - ./log:/var/log/letsencrypt:z
  #     - ./dnspod.conf:/opt/certbot/dnspod.conf:ro
  #   command:
  #     # 首次部署需要执行该容器生成证书
  #     - sh
  #     - -c
  #     - |
  #         certbot certonly -a dns-dnspod \
  #         --certbot-dns-dnspod:dns-dnspod-credentials /opt/certbot/dnspod.conf \
  #         --preferred-challenges dns --server https://acme-v02.api.letsencrypt.org/directory \
  #         -m darebeat@126.com \
  #         -d *.darebeat.cn \
  #         -d darebeat.cn
  #   entrypoint: ""
      

  certbot-dnspod-renew:
    image: darebeat/certbot
    container_name: certbot-dnspod-renew
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./etc:/etc/letsencrypt:z
      - ./lib:/var/lib/letsencrypt:z
      - ./log:/var/log/letsencrypt:z
      - ./dnspod.conf:/opt/certbot/dnspod.conf:ro
    command: 
      - sh
      - -c
      - |
          crontab -l >> /cronfig
          echo "1 1 1 * * certbot renew >> /var/log/renew.log" >> /cronfig
          crontab /cronfig
          touch /var/log/renew.log
          crond
          tail -f /var/log/renew.log
    entrypoint: ""
          
networks:
  deploy:
    external: true