version: "3"

services:
  certbot:
    image: darebeat/certbot
    container_name: certbot
    env_file:
      - .env
    environment: 
      - CERT_START_MODE=renew-auto # crontab控制初始化或自动续期
      - CERT_DNS_VENDOR=hwy # dnspod|hwy|txy|aly|godaddy
      - CERT_EMAIL=darebeat@126.com
      - CERT_REQ_DOMAINS="darebeat.cn,*.darebeat.cn,*.blog.darebeat.cn" # 多个域名用英文逗号隔开
      - CERT_CRON_TIME="1 1 1 * *"
      - CERT_LOG_DIR=/var/log
      - TZ=Asia/Shanghai
    volumes:
      - ./etc:/etc/letsencrypt:z
      - ./lib:/var/lib/letsencrypt:z
      - ./log:/var/log/letsencrypt:z
      - ./domains:/opt/certbot/certbot-dns-cnyun/domains:ro
      # - ./docker-entrypoint.sh:/docker-entrypoint.sh # 可以根据需要调整脚本
    entrypoint: /docker-entrypoint.sh # 覆盖镜像默认指令
    command: 
      - renew-auto  # 同CERT_START_MODE,可以任选其一进行配置(这个优先级高)
      - hwy         # 同CERT_DNS_VENDOR,可以任选其一进行配置(这个优先级高)