version: '2'
services:
  mongodb:
    image: mongo:3.2.16
    container_name: mongodb
    ports:
        - 27017:27017
    command: mongod --auth --dbpath /data/db --port 27017

networks:
  default:
    external:
      name: share
