version: '3'
services:
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    networks:
      deploy:
        ipv4_address: 172.10.0.101
        aliases:
          - mysql57
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test0755
      - MYSQL_DATABASE=test
      - TZ=Asia/Shanghai
    volumes:
      - ./db:/var/lib/mysql:rw
      - ./src/config/mysqld.cnf::/etc/my.cnf:ro
    tty: true

networks:
  deploy:
    external: true