version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - "~/data/mysql:/var/lib/mysql"
    tty: true

networks:
  default:
    external:
      name: share
