version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
      deploy:
        ipv4_address: 172.10.0.101
        aliases:
          - mysql
    ports:
      - "3310:3306"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./db:/var/lib/mysql:rw
      - ./src/config/mysqld.cnf:/etc/my.cnf:ro
    tty: true

networks:
  deploy:
    external: true