version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    networks:
      deploy:
        ipv4_address: 172.10.0.2
        aliases:
          - frpc
    # extra_hosts:
    #   - "jobmanager:172.10.0.2"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - "~/data/mysql:/var/lib/mysql"
      - "./src/config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
    tty: true

networks:
  deploy:
    external: true
