version: '3'
services:
  o_mysql:
    image: mysql:5.7
    container_name: o_mysql
    restart: always
    networks:
      deploy:
        ipv4_address: 172.10.0.117
        aliases:
          - mysql
    ports:
      - "3309:3306"
    env_file:
      - .env_mysql
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/mysql.conf:/etc/my.cnf:ro
      - ./db:/var/lib/mysql:rw
      - ./sql/oneblog.sql:/docker-entrypoint-initdb.d/oneblog.sql:ro
    tty: true

networks:
  deploy:
    external: true