version: '3'
services:
  o_redis:
    image: redis:6.0.10-alpine
    container_name: o_redis
    networks:
      deploy:
        ipv4_address: 172.10.0.118
        aliases:
          - redis
    ports:
      - 6379:6379
    command: redis-server /etc/redis.conf
    volumes:
      - ./conf/redis.conf:/etc/redis.conf  

networks:
  deploy:
    external: true