version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
    networks:
      deploy:
        ipv4_address: 172.10.0.3
        aliases:
          - redis
    tty: true

networks:
  deploy:
    external: true