version: "3"
services:
  wow60-database:
    image: registry.cn-shenzhen.aliyuncs.com/olivercj/wow60-database:0.1
    container_name: wow60-database
    command:
      - /run.sh
    ports:
      - 3306:3306/tcp
    networks:
      deploy:
        ipv4_address: 172.10.0.114
        aliases:
          - wow60-database
  wow60-realmd:
    image: registry.cn-shenzhen.aliyuncs.com/olivercj/wow60-realmd:0.2
    container_name: wow60-realmd
    command:
      - /data/run.sh
    ports:
      - 3724:3724/tcp
    depends_on:
      - wow60-database
    networks:
      deploy:
        ipv4_address: 172.10.0.115
        aliases:
          - mysql
  wow60-world-0:
    image: registry.cn-shenzhen.aliyuncs.com/olivercj/wow60-world:0.2
    container_name: wow60-world-0
    command:
      - /data/run.sh
    ports:
      - 8085:8085/tcp
    depends_on:
      - wow60-realmd
    networks:
      deploy:
        ipv4_address: 172.10.0.116
        aliases:
          - mysql

networks:
  deploy:
    external: true