version: '3'
services:
  mysql:
    image: daocloud.io/darebeat/jenkins
    container_name: jenkins
    networks:
      deploy:
        ipv4_address: 172.10.0.108
        aliases:
          - jenkins
    ports:
      - "8089:8080"   

networks:
  deploy:
    external: true