version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d:/etc/nginx/conf.d:z
      - ../certbot/etc:/etc/nginx/certs:z
