version: '3'
services:
  chevereto:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d/upstream-all.conf:/etc/nginx/conf.d/upstream-all.conf
      - ./conf/conf.d/http-all.conf:/etc/nginx/conf.d/http-all.conf
