version: '3'
services:
  chevereto:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 10104:80