version: '3'
services:
  chevereto:
    image: nmtan/chevereto
    container_name: chevereto
    hostname: chevereto
    restart: always
    networks:
      deploy:
        ipv4_address: 172.10.0.103
        aliases:
          - chevereto
    extra_hosts:
      - "mysql:172.10.0.101"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    external_links:
      - mysql
    volumes:
      - ./html:/var/www/html/html:rw
      - ./conf/upload.ini:/usr/local/etc/php/conf.d/upload.ini:ro
    ports:
      - 10103:80

networks:
  deploy:
    external: true