version: "3"
services:
  jobmanager:
    image: ${FLINK_VERSION:-darebeat/flink:1.12.0-scala_2.11}
    ports:
      - "8081:8081"
    command: standalone-job --job-classname com.job.ClassName [--job-id <job id>] [--fromSavepoint /path/to/savepoint [--allowNonRestoredState]] [job arguments]
    container_name: flink-jobmanager
    hostname: jobmanager
    networks:
      deploy:
        ipv4_address: 172.10.0.2
        aliases:
          - jobmanager
    volumes:
      - ./artifacts:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 2

  taskmanager:
    image: ${FLINK_VERSION:-darebeat/flink:1.12.0-scala_2.11}
    depends_on:
      - jobmanager
    command: taskmanager
    container_name: flink-taskmanager
    hostname: taskmanager
    networks:
      deploy:
        ipv4_address: 172.10.0.3
        aliases:
          - taskmanager
    scale: 1
    volumes:
      - ./artifacts:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 2

  edge:
    image: netcat # 需要自己手动build
    container_name: flink-edge
    hostname: edge
    networks:
      deploy:
        ipv4_address: 172.10.0.100
        aliases:
          - edge

networks:
  deploy:
    external: true