# export FRP_NODE=frps && docker-compose config
version: "3"
services:
  frp:
    image: darebeat/frp:${FRP_VERSION:-0.34.1}
    command: ${FRP_NODE:-frps}
    container_name: ${FRP_NODE:-frps}
    ports:
      - "17000:17000"
      - "17500:17500"
      - "10022:10022" # ssh 
      - "13307:13307" # mysql
      - "18080:18080" # web
      - "13000:13000" # web
      - "19000:19000" # flink
    volumes:
      - ./conf/${FRP_NODE:-frps}.ini:/opt/frp/conf/${FRP_NODE:-frps}.ini