version: '3'
services:
  zk:
    image: zookeeper:${ZK_VERSION:-3.5}
    container_name: zk
    hostname: zk
    networks:
      deploy:
        ipv4_address: 172.10.0.80
    environment:
      - TZ=Asia/Shanghai

  ch1:
    image: yandex/clickhouse-server:${CK_VERSION:-20.8.11.17}
    container_name: ch1
    hostname: ch1
    networks:
      deploy:
        ipv4_address: 172.10.0.81
    environment:
      - TZ=Asia/Shanghai
      - SHARD=01
      - REPLICA=ch1
    command:
      - bash
      - -c
      - |
        cat > /etc/clickhouse-server/config.d/macros.xml << EOF
        <yandex>
          <macros>
            <shard>${SHARD:-01}</shard>
            <replica>${REPLICA:-ch1}</replica>
          </macros>
        </yandex>
        EOF
        /entrypoint.sh
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - ./data/ch1:/var/lib/clickhouse:rw
      - ./conf/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./conf/dictionary.xml:/etc/clickhouse-server/dictionary.xml:ro
      - ./conf/metrika.xml:/etc/clickhouse-server/metrika.xml:ro
      - ./conf/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./log/log_01:/var/log/clickhouse-server:rw
    depends_on:
      - zk

  ch2:
    image: yandex/clickhouse-server:${CK_VERSION:-20.8.11.17}
    container_name: ch2
    hostname: ch2
    networks:
      deploy:
        ipv4_address: 172.10.0.82
    environment:
      - TZ=Asia/Shanghai
      - SHARD=01
      - REPLICA=ch2
    command:
      - bash
      - -c
      - |
        cat > /etc/clickhouse-server/config.d/macros.xml << EOF
        <yandex>
          <macros>
            <shard>${SHARD:-01}</shard>
            <replica>${REPLICA:-ch2}</replica>
          </macros>
        </yandex>
        EOF
        /entrypoint.sh
    volumes:
      - ./data/ch2:/var/lib/clickhouse:rw
      - ./conf/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./conf/dictionary.xml:/etc/clickhouse-server/dictionary.xml:ro
      - ./conf/metrika.xml:/etc/clickhouse-server/metrika.xml:ro
      - ./conf/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./log/log_02:/var/log/clickhouse-server:rw
    depends_on:
      - zk

  ch3:
    image: yandex/clickhouse-server:${CK_VERSION:-20.8.11.17}
    container_name: ch3
    hostname: ch3
    networks:
      deploy:
        ipv4_address: 172.10.0.83
    environment:
      - TZ=Asia/Shanghai
      - SHARD=02
      - REPLICA=ch3
    command:
      - bash
      - -c
      - |
        cat > /etc/clickhouse-server/config.d/macros.xml << EOF
        <yandex>
          <macros>
            <shard>${SHARD:-02}</shard>
            <replica>${REPLICA:-ch3}</replica>
          </macros>
        </yandex>
        EOF
        /entrypoint.sh
    volumes:
      - ./data/ch3:/var/lib/clickhouse:rw
      - ./conf/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./conf/dictionary.xml:/etc/clickhouse-server/dictionary.xml:ro
      - ./conf/metrika.xml:/etc/clickhouse-server/metrika.xml:ro
      - ./conf/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./log/log_03:/var/log/clickhouse-server:rw
    depends_on:
      - zk

  ch4:
    image: yandex/clickhouse-server:${CK_VERSION:-20.8.11.17}
    container_name: ch4
    hostname: ch4
    networks:
      deploy:
        ipv4_address: 172.10.0.84
    environment:
      - TZ=Asia/Shanghai
      - SHARD=02
      - REPLICA=ch4
    command:
      - bash
      - -c
      - |
        cat > /etc/clickhouse-server/config.d/macros.xml << EOF
        <yandex>
          <macros>
            <shard>${SHARD:-02}</shard>
            <replica>${REPLICA:-ch4}</replica>
          </macros>
        </yandex>
        EOF
        /entrypoint.sh
    volumes:
      - ./data/ch4:/var/lib/clickhouse:rw
      - ./conf/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./conf/dictionary.xml:/etc/clickhouse-server/dictionary.xml:ro
      - ./conf/metrika.xml:/etc/clickhouse-server/metrika.xml:ro
      - ./conf/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./log/log_04:/var/log/clickhouse-server:rw
    depends_on:
      - zk

networks:
  deploy:
    external: true