version: '3'
services:
  mblog:
    image: darebeat/mblog
    container_name: mblog
    networks:
      deploy:
        ipv4_address: 172.10.0.105
        aliases:
          - mblog
    extra_hosts:
      - "mysql:172.10.0.101"
    environment:
      TZ: Asia/Shanghai
    env_file:
      - .env
    command: mysql
    external_links:
      - mysql
    ports:
      - "10104:8080"
    volumes:
      - ./data:/app/mblog/storage:rw
      - ./logs:/app/mblog/logs:rw
    restart: always

networks:
  deploy:
    external: true