version: '3'
services:
  kiftd:
    image: darebeat/kiftd
    container_name: kiftd
    networks:
      deploy:
        ipv4_address: 172.10.0.18
        aliases:
          - kiftd
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8081:8080"

networks:
  deploy:
    external: true