version: '2'
services:
  oracle:
    image: truevoly/oracle-12c
    container_name: oracle
    networks:
      deploy:
        ipv4_address: 172.10.0.106
        aliases:
          - oracle
    ports:
      - 49161:1521
      - 8080:8080
    environment:
      - DBCA_TOTAL_MEMORY=4096
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=true
    # volumes:
    #   - ./data:/u01/app/oracle

networks:
  deploy:
    external: true