version: '2'
services:
  oracle:
    image: daocloud.io/darebeat/oracle-xe-11g
    container_name: oracle
    networks:
      deploy:
        ipv4_address: 172.10.0.106
        aliases:
          - oracle
    ports:
      - 49161:1521
      - 8080:8080
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=true

networks:
  deploy:
    external: true