version: '3'
services:
  odoo_web:
    image: odoo:12.0
    container_name: odoo_web
    restart: always
    depends_on:
      - odoo_db
    networks:
      deploy:
        ipv4_address: 172.10.0.20
        aliases:
          - odoo_web
    extra_hosts:
      - "odoo_db:172.10.0.19"
    ports:
      - "8069:8069"
    environment:
      - TZ=Asia/Shanghai
      - HOST=odoo_db
      - PORT=5432
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  odoo_db:
    image: postgres:10
    container_name: odoo_db
    networks:
      deploy:
        ipv4_address: 172.10.0.19
        aliases:
          - odoo_db
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=myodoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata

networks:
  deploy:
    external: true