version: '3'
services:
  hadoop:
    image: sequenceiq/hadoop-docker:2.7.1
    container_name: hdfs
    networks:
      deploy:
        ipv4_address: 172.10.0.199
        aliases:
          - hdfs
    extra_hosts:
      - "hdfs:172.10.0.199"
    ports:
      # sshd
      - "2122:2122"
      # Yarn ports
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8033:8033"
      - "8040:8040"
      - "8042:8042"
      - "8088:8088"
      # Mapred ports
      - "10020:10020"
      - "19888:19888"
      # Hdfs ports
      - "8020:8020"
      - "9000:9000"
      - "50010:50010"
      - "50020:50020"
      - "50070:50070"
      - "50075:50075"
      - "50090:50090"
      # other
      - "49707:49707"  
    environment:
      - TZ=Asia/Shanghai
      - HOSTNAME=hdfs
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/default/bin:/usr/local/hadoop/bin

networks:
  deploy:
    external: true