version: '3'
services:
  master:
    image: daocloud.io/darebeat/hadoop
    ports:
      - 50060:8088
      - 50070:50070
    container_name: hadoop-master
    hostname: hadoop-master
    env_file:
      - .env
    volumes:
      - ./src/config/hdfs-site.xml:${HADOOP_PATH:-/usr/local}/etc/hadoop/hdfs-site.xml
      - ./src/config/core-site.xml:${HADOOP_PATH:-/usr/local}/etc/hadoop/core-site.xml
      - ./src/config/mapred-site.xml:${HADOOP_PATH:-/usr/local}/etc/hadoop/mapred-site.xml
      - ./src/config/yarn-site.xml:${HADOOP_PATH:-/usr/local}/etc/hadoop/yarn-site.xml
      - ./src/config/slaves:${HADOOP_PATH:-/usr/local}/etc/hadoop/slaves
    entrypoint: wait-for -d hadoop-slave1:22,hadoop-slave2:22 -c '/bootstrap.sh'
  slave1:
    image: daocloud.io/darebeat/hadoop
    container_name: hadoop-slave1

  slave2:
    image: daocloud.io/darebeat/hadoop
    container_name: hadoop-slave2

networks:
  default:
    external:
      name: share
