version: '3'
services:
  es:
    image: elasticsearch:7.3.0
    container_name: es
    restart: always
    networks:
      deploy:
        ipv4_address: 172.10.0.11
        aliases:
          - es
    environment:
      - cluster.name=es   #集群名称为 elasticsearch
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #jvm内存分配为512MB
      - "discovery.type=single-node" #单节点启动
      - "TZ=Asia/Shanghai"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
      - ./conf.d/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: kibana:7.3.0
    container_name: kibana
    networks:
      deploy:
        ipv4_address: 172.10.0.12
        aliases:
          - kibana
    extra_hosts:
      - "es:172.10.0.11"
    depends_on:
      - es
    environment:
      - "elasticsearch.hosts=http://es:9200"
    ports:
      - 5601:5601

  logstash:
    image: logstash:7.3.0
    container_name: logstash
    networks:
      deploy:
        ipv4_address: 172.10.0.13
        aliases:
          - logstash
    extra_hosts:
      - "es:172.10.0.11"
    depends_on:
      - es
    ports:
      - 4560:4560
    volumes:
      - ./conf.d/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

networks:
  deploy:
    external: true