version: '3'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    networks:
      deploy:
        ipv4_address: 172.10.0.20
        aliases:
          - mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress0755
      - MYSQL_DATABASE=wordpress
      - TZ=Asia/Shanghai
    volumes:
      - ./my.cnf:/etc/my.cnf
      - db_data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    networks:
      deploy:
        ipv4_address: 172.10.0.21
        aliases:
          - wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress

networks:
  deploy:
    external: true
