version: '3'
services:
  wordpress-hyj:
    container_name: wordpress-hyj
    image: wordpress:latest
    ports:
      - "10102:80"
    restart: always
    networks:
      deploy:
        ipv4_address: 172.10.0.112
        aliases:
          - wordpress-hyj
    extra_hosts:
      - "mysql:172.10.0.110"
    env_file:
      - .env_wp_all
    environment:
      - TZ=Asia/Shanghai
    external_links:
      - mysql
    volumes:
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - ./html/wp-content-yj:/var/www/html/wp-content:rw

networks:
  deploy:
    external: true

