version: '3'
services:
  jpress_db:
    image: mysql:5.7
    container_name: jpress_db
    restart: always
    security_opt:
      - seccomp:unconfined
    networks:
      deploy:
        ipv4_address: 172.10.0.21
        aliases:
          - jpress
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: jpress
      MYSQL_DATABASE: jpress
      MYSQL_USER: jpress
      MYSQL_PASSWORD: jpress
    volumes:
      - "./docker_volumes/mysql:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password

networks:
  deploy:
    external: true