version:  '3'
services:
  master:
    image: daocloud.io/darebeat/hadoop
    container_name: hadoop-master
    networks:
      cluster:
        ipv4_address: 172.20.0.2
        aliases:
          - hadoop-master
    volumes:
      - ./src/config/hdfs-site.xml:${HADOOP_PATH:-/usr/local}/etc/hadoop/hdfs-site.xml
      - ./src/config/core-site.xml:${HADOOP_PATH:-/usr/local}/etc/hadoop/core-site.xml
      - ./src/config/mapred-site.xml:${HADOOP_PATH:-/usr/local}/etc/hadoop/mapred-site.xml
      - ./src/config/yarn-site.xml:${HADOOP_PATH:-/usr/local}/etc/hadoop/yarn-site.xml
      - ./src/config/masters:${HADOOP_PATH:-/usr/local}/etc/hadoop/masters
      - ./src/config/slaves:${HADOOP_PATH:-/usr/local}/etc/hadoop/slaves
    extra_hosts:
      - "slave1:172.20.0.3"
      - "slave2:172.20.0.4"
    hostname: master
    ports:
      - 8088:8088
      - 50070:50070
    entrypoint: wait-for -d slave1:22,slave2:22 -c '/bootstrap.sh'
    environment:
      ROLE: master

  slave1:
    image: daocloud.io/darebeat/hive
    container_name: hadoop-slave1
    networks:
      cluster:
        ipv4_address: 172.20.0.3
        aliases:
          - hadoop-slave1
    extra_hosts:
      - "master:172.20.0.2"
      - "slave2:172.20.0.4"
    hostname: slave1
    environment:
      ROLE: slave

  slave2:
    image: daocloud.io/darebeat/hive
    container_name: hadoop-slave2
    networks:
      cluster:
        ipv4_address: 172.20.0.4
        aliases:
          - hadoop-slave2
    extra_hosts:
      - "master:172.20.0.2"
      - "slave1:172.20.0.3"
    hostname: slave2
    environment:
      ROLE: slave

networks:
  cluster:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
